server:
    mode: ${ORGANIZE_TOYS_SERVER_MODE} # 服务器模式，默认为 dev
insecure:
    bind-address: ${ORGANIZE_TOYS_SERVER_INSECURE_BIND_ADDRESS} # 绑定的不安全 IP 地址，设置为 0.0.0.0 表示使用全部网络接口，默认为 127.0.0.1
    bind-port: ${ORGANIZE_TOYS_SERVER_INSECURE_BIND_PORT} # 提供非安全认证的监听端口，默认为 8001
