insecure:
    bind-address: ${ORGANIZE_TOYS_SERVER_INSECURE_BIND_ADDRESS:-0.0.0.0} # 绑定的不安全 IP 地址，设置为 0.0.0.0 表示使用全部网络接口，默认为 127.0.0.1
    bind-port: ${ORGANIZE_TOYS_SERVER_INSECURE_BIND_PORT:-8001} # 提供非安全认证的监听端口，默认为 8001
logs:
    log-file: ${NEXUS_POINT_WG_LOGS_LOG_FILE:-logs/NexusPointWG.log}
    log-max-size: ${NEXUS_POINT_WG_LOGS_LOG_MAX_SIZE:-100}
    log-max-backups: ${NEXUS_POINT_WG_LOGS_LOG_MAX_BACKUPS:-3}
    log-max-age: ${NEXUS_POINT_WG_LOGS_LOG_MAX_AGE:-28}
    log-compress: ${NEXUS_POINT_WG_LOGS_LOG_COMPRESS:-true}
sqlite:
    data-source-name: ${NEXUS_POINT_WG_SQLITE_DATA_SOURCE_NAME:-./nexuspointwg.db}
wireguard:
    root-dir: ${NEXUS_POINT_WG_WIREGUARD_ROOT_DIR:-/etc/wireguard}
    interface: ${NEXUS_POINT_WG_WIREGUARD_INTERFACE:-wg0}
    user-dir: ${NEXUS_POINT_WG_WIREGUARD_USER_DIR:-user}
    endpoint: ${NEXUS_POINT_WG_WIREGUARD_ENDPOINT:-0.0.0.0:51820}
    dns: ${NEXUS_POINT_WG_WIREGUARD_DNS:-}
    default-allowed-ips: ${NEXUS_POINT_WG_WIREGUARD_DEFAULT_ALLOWED_IPS:-0.0.0.0/0,::/0}
    apply-method: ${NEXUS_POINT_WG_WIREGUARD_APPLY_METHOD:-systemctl}